Common: Entity (de)serialization, instead JsonUnwrapped annotation, which is not working with record.
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot define Creator property "id" as `@JsonUnwrapped`: combination not yet supported